# Traffic 真实数据集配置
# 基于实际的 traffic.csv 文件 (862个传感器道路占用率)

data:
  dataset_name: "traffic"
  data_path: "m2moep/dataset/traffic_862个传感器测量的每小时道路占用率/traffic.csv"
  seq_len: 96
  pred_len: 24
  features: "M"  # multivariate
  target: "Sensor_861"      # 通常最后一个传感器
  # 训练数据配置
  train_ratio: 0.7
  val_ratio: 0.2
  test_ratio: 0.1
  # 数据加载配置
  batch_size: 2             # 最小批次（862个特征非常多）
  num_workers: 2
  pin_memory: true
  # 数据处理配置
  scaler_type: "standard"
  normalize: true
  inverse: false
  standardize: true
  
model:
  model_name: "M2_MOEP"
  
  # 基础模型参数 - 针对超高维数据（862个传感器）
  input_dim: 862            # Traffic数据集特征数
  output_dim: 862
  hidden_dim: 256           # 进一步增加隐藏层维度
  seq_len: 96
  pred_len: 24
  
  # 专家系统参数
  num_experts: 8            # 最多专家处理超高维数据
  top_k: 4
  embedding_dim: 512        # 大幅增加嵌入维度
  
  # 专家网络参数
  expert_params:
    mamba_d_model: 256      # 大幅增加模型维度
    mamba_scales: [1, 2, 4, 8, 16]
    
  # 温度调度参数
  temperature:
    initial: 2.0            # 更低的初始温度
    min: 0.3
    max: 5.0
    decay_rate: 0.99
    
  # Flow模型参数
  flow:
    num_layers: 8
    hidden_dim: 512
    latent_dim: 1024
    input_dim: 82752         # 862 * 96
    use_pretrained: true
    
training:
  # 基础训练参数
  batch_size: 2
  learning_rate: 0.00003    # 非常小的学习率
  epochs: 20                # 更少轮数（超大数据集）
  
  # 优化器参数
  optimizer: "adamw"
  weight_decay: 0.01
  beta1: 0.9
  beta2: 0.999
  eps: 1e-8
  
  # 学习率调度
  scheduler: "cosine"
  lr_min: 1e-8
  warmup_epochs: 2
  
  # 梯度控制
  gradient_clip: 0.2        # 非常严格的梯度裁剪
  use_amp: false
  
  # 损失函数权重
  loss_weights:
    prediction: 1.0
    reconstruction: 0.02    # 最小重构损失权重
    triplet: 0.01
  
  # 训练策略
  use_reconstruction_loss: true
  use_triplet_loss: true
  
  # 三元组损失参数
  triplet_margin: 0.05
  triplet_mining: "batch_hard"
  
  # 验证和保存设置
  val_check_interval: 1
  save_top_k: 1             # 只保存最好的模型
  
  # 早停设置
  early_stopping:
    patience: 5
    min_delta: 0.0001
    
  # 数值稳定性设置
  numerical_stability:
    loss_clamp_max: 5.0
    grad_norm_threshold: 0.5
    nan_detection: true
    
# 输出设置
output:
  save_dir: "checkpoints"
  log_dir: "logs"
  result_dir: "results"
  
# 设备设置
device: "cuda"
seed: 42

# 调试设置
debug:
  log_gradients: true
  check_numerical: true
  profile_memory: true      # 必须监控内存
  
# 实验设置
experiment:
  name: "traffic_real_data"
  description: "Traffic数据集（862个传感器）真实数据训练"
  tags: ["traffic", "real_data", "ultra_high_dimensional"] 